name: Compilation CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Update and Install Dependencies
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libunwind-dev libxcursor-dev \
          libxrandr-dev \
          libxinerama-dev \
          libxi-dev \
          libgl1-mesa-dev \
          libglu1-mesa-dev \
          zlib1g-dev \
          libfontconfig1-dev \
          libmpg123-dev \
          libsndfile1 \
          libsndfile1-dev \
          libpulse-dev \
          libasound2-dev \
          libcurl4-gnutls-dev \
          libgstreamer1.0-dev \
          libgstreamer-plugins-bad1.0-dev \
          libgstreamer-plugins-base1.0-dev \
          gstreamer1.0-libav \
          gstreamer1.0-alsa \
          gstreamer1.0-pulseaudio \
          gstreamer1.0-plugins-bad \
          libboost-filesystem-dev

    - name: Compile
      run: |
        git submodule update --init --recursive
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make
